### ISSUE TITLE
company-complete error

### ISSUE THREAD

**Issue by vegansk** [nim-lang/nim-mode#137]
When I call ``company-complete`` after the dot:
![image](https://cloud.githubusercontent.com/assets/2908508/18460269/410e21c0-799a-11e6-97b2-48547d0ba542.png)
, it fails with the message:
```
Company: backend company-nim error "Wrong type argument: stringp, nil" with args (prefix)
```

If there is at least one letter, it works:
![image](https://cloud.githubusercontent.com/assets/2908508/18460295/7391de66-799a-11e6-949b-8a0d1b7b4888.png)

**Comment by yuutayamada** [comment]
Please update nim-mode the bug was fixed. (if you are using MELPA, you may need to wait until MELPA is updated)

Also, latest version's configuration has slightly changed.

If you have following configuration, you can remove:

```lisp
(add-to-list 'company-backends
               '(company-nim :with company-nim-builtin))
```

instead you need following configuration to use nimsuggest integration:

```lisp
(add-hook 'nim-mode-hook 'nimsuggest-mode)
```

Thank you for conforming the bug :)

**Comment by vegansk** [comment]
Thanks. Now, after nim-mode update, it doesn't use company anymore. Is it by design?
![image](https://cloud.githubusercontent.com/assets/2908508/18466576/75087c6a-79c6-11e6-96c7-0ad00b452747.png)

**Comment by vegansk** [comment]
Anyway, the concrete problem is gone. Thanks!

**Comment by yuutayamada** [comment]
>  Now, after nim-mode update, it doesn't use company anymore. Is it by design?

Yes (I mean no dependencies) but you can still use company-mode as almost same functionality as before because company-mode has `company-capf` backend, which support completion for Emacs' standard completion method `Completion-At-Point-Functions` (M-/ key).

if you already have `(add-hook 'nim-mode-hook 'company-mode)` configuration, please make sure the value of `company-backends` whether it includes `company-capf`.

or if you are using company-flx, please turn off it during nim-mode. I tried it, but somehow it doesn't work well.
