### ISSUE TITLE
suggestions for included files

### ISSUE THREAD

**Issue by krux02** [nim-lang/nim-mode#152]
I have several files in my project, that I include in my root file. When I am edititng these files, flycheck just doesn't know the context for these files at all, and therefore everything becomes red. Is there a way to configure/customize do something, to get the right error messages. Worst case would be a way to at least disable flycheck in just these buffers.

**Comment by krux02** [comment]
I found out by looking through the sourcecode, that nim-suggest calls ``(nim-find-project-path)``. This function returns nil, when I do not have a config file, or otherwise ``"myproject.nim.cfg"``. That cfg file is then used as an argument for nimsuggest. The effect is, that there are no errors at all anymore. Why is a cfg file passed to nimsuggest? What is supposed to be in this cfg file?

**Comment by yuutayamada** [comment]
Sorry for late reply.
AFAIR, I implemented that because of that I saw configuration file section of https://nim-lang.org/docs/nimc.html. (or maybe it was already exist before I joined nim-mode) and I thought the place where XXX.nim.cfg exists could be project root.
But I'm not sure really, so PR are welcome.

**Comment by yuutayamada** [comment]
seems nimsuggest doen't work if it was passed myproject.nim.cfg, so I just deleted the logic.

**Comment by yuutayamada** [comment]
@krux02 Ah sorry, I didn't intend to close this issue, please feel free to re-open if you still have trouble.
